// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXD3_kgOtvYLUgQEFpe9o8Sc0yTqKM29M',
    appId: '1:53475165465:web:cb50a28b57a9e70ca3f188',
    messagingSenderId: '53475165465',
    projectId: 'aprendendoseginfo',
    authDomain: 'aprendendoseginfo.firebaseapp.com',
    storageBucket: 'aprendendoseginfo.appspot.com',
    measurementId: 'G-C5VCV1HBTK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOR-Y9boCGqXI11iMPK1M8uzrTJs76BqM',
    appId: '1:53475165465:android:a44863fda6b5838aa3f188',
    messagingSenderId: '53475165465',
    projectId: 'aprendendoseginfo',
    storageBucket: 'aprendendoseginfo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6un8NtAdAtis7JbWOHbOBSeb7KwNsTRw',
    appId: '1:53475165465:ios:d6c05e7c3d31d479a3f188',
    messagingSenderId: '53475165465',
    projectId: 'aprendendoseginfo',
    storageBucket: 'aprendendoseginfo.appspot.com',
    iosClientId: '53475165465-89h2vrhartikih2aspe5gr3phj7ctc14.apps.googleusercontent.com',
    iosBundleId: 'com.example.gameTemplate',
  );
}
