// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC13hRvmfYzBAsv2JNvE1VwjdWPfTtjQgY',
    appId: '1:213460055585:web:35729efa397ee3c5bfd560',
    messagingSenderId: '213460055585',
    projectId: 'learninginformationsecurity',
    authDomain: 'learninginformationsecurity.firebaseapp.com',
    storageBucket: 'learninginformationsecurity.appspot.com',
    measurementId: 'G-PH4DQZBTP8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzMq-HM3E80JbemAKjnF3Tgqq2ArX3pCc',
    appId: '1:213460055585:android:66d17b91644274aabfd560',
    messagingSenderId: '213460055585',
    projectId: 'learninginformationsecurity',
    storageBucket: 'learninginformationsecurity.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtM-ZAJIVnmb-H-REDYTenLUqEHW46H24',
    appId: '1:213460055585:ios:bb527ccffec01ab1bfd560',
    messagingSenderId: '213460055585',
    projectId: 'learninginformationsecurity',
    storageBucket: 'learninginformationsecurity.appspot.com',
    androidClientId: '213460055585-rar3utet5f8urqn3usghpees89a7ac7o.apps.googleusercontent.com',
    iosClientId: '213460055585-8j5eaiv8bjrrdkqrsl71formdb6pf432.apps.googleusercontent.com',
    iosBundleId: 'com.example.gameTemplate',
  );
}
